# Generated by Django 2.2.1 on 2019-05-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_gold'),
        ('songList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='songList.Song')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='users.User')),
            ],
        ),
    ]
